sudo: false
language: node_js
node_js:
- 5.6
cache:
  directories:
  - node_modules
before_install:
- npm install codecov.io coveralls
after_success:
- cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
- npm run build
branches:
  only:
  - master
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: iNPM0b8AvHmE+FyPlPyzea20m0bp1odqwXKmE4mlV1vBOLVmCzVuBq1LeYb6FWQIiwcCGTLKNxKS6e6duNYql0ZlVcj0uSrT2dxu5/beWioRdVekZEFgw8hZKTZlXw1B/H6xzd1WCDjtkYFG9gooNxSheTeQ+k/spLkR5MXSSUSAb1T4PsdA2gNstNPai9v7sci4x5AwFL+ghZwBYWYVRvi/nWOfLHB0nTiqqBKtgFPGSJtEwXxkN5aBwTjeomFqpEE5MMOlNvA49l6W2fziNCX9WopG1E7ZIkQV6hyuEMuxFNkSQUY6zI54ehws6BMLPa6ULY3KyLr6B3N2+6wAGd2FxzkRN5s9w94tBWX+oBvCDlgxeQf9OwyX/5N690O04b5rNm+uHRcPuf7Jw80CXvhvJ5lLGrt/bVNVCy0pUIJzJA17o5i4oaeXRHdkgoX0QVDDb+NhEF8rLpfDG+Qxne2zl0jdF+sQG4HaZc6fplqlyXFSTwRG6T7rPVP0op0gbpeIDo8MGYxYAZh32l3F6aT03eDyq9C6HD4aa8NPd9qjNHE2UBgxk9agW/yp+3glk+QRI0qt05oWm3Q6MZ5gLggkQ72TP0K9EiylFSjltXQrId20LpDADT+R5xNk1k25IdSPgrNuyDvl9Xph7yQ6/5fgeq0ppprsB1F4xEYsQWY=
