sudo: false
language: node_js
node_js:
- 5.6
cache:
  directories:
  - node_modules
before_install:
- npm install codecov.io coveralls
after_success:
- cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
- npm run build
branches:
  only:
  - master
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: osr2suUsZG2oZO4GXgbEDFTh3NbSaICtUH8bnKPKPLH+YfCoqyHWlf0B0yEu7Y4FJEnjtB+Ipht7Krdyxa34zOMjgKPk+ox4iuvR3A/0q3FMvipcVnqhR8N0Wt07e+euXXpB07Cb8k8lNd2RZS98/Va3dFOgJDmvqDSe/7TGYxeXHJf4TGaERr2eTiCC0jLfvIgqSBSpklGsxyJKqzYmHaouMdTQKO+9QaMt/JUovFWP2AA3xNO4mBaGod0gtrM1pFXnix8MMQJG/6SnIE5CgSFRf69b+hG5at6sNuGG+1RIa23344qgLAclB7tWgvXdGve8SMJLtgxnBloS8ZI+XKJBcFYvtEyZacCoCBPbCxPW2Q/dvCAffoPI2MqtPcEVqX1pjk6WVcbLGt7nrpzVFaNHxs2arnwBUk9LyH6jEJIcBREeom9YZTUqq0VJVoqfS42MtT1jdsIXWX5lumXt7w3yKiXeOLTdK9O5dNBCD+IVbJ6VrUnFHRCBVjIxMWT7DQDdkntyskmROaDVjNO4biElmTPQY+FZpXBS6LCP7D59Pzz9/QbI6ERywOihKbifgHKLlOsgwLDWXznJXjcdzCt01C4e399Td8FeiOsPpkPX5VHOJY9WWgeNGHzopNNJ9CCIg1bBYdNnNkqU/zC5m+EcUI4jv3oXs/hYgVB7xso=
