sudo: false
language: node_js
node_js:
- 5.6
cache:
  directories:
  - node_modules
before_install:
- npm install codecov.io coveralls
after_success:
- cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
- npm run build
branches:
  only:
  - master
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: wL/yDEhXXHocd6x3vkfYQTlKHK5WEEyMucZwESVoqUMIGWb25dmHJp9bA54qiPdofsk0p3Hal7saVM9qGwD46VRO61cGaNM0I8YiLqKNc251XVOKrdRc8wunBv9pgTkFLbWYw1Mj79ghB1OllEeIfL/3C4t3FHAzLaiVd5tPZnLkiuInFSFzgSRqz17XpZQqUDFCCg2Re85pR4gX5yCny6+DNL49ZyKOFjBHZKeeOA/7YR9XyanLZjLq4yZBVdPUzZghU29yNWtNgskqxm3Wt4OZMdxIR4x1CqZnAFw2VEal+RODcEXJQWJfggHadGTh1bhNXgmJwBeqQh/Djsc8IZVOObeetdS/fVL+xzAcbAzTa8kQAL3JT67WnghsTGq0Huy/GwzuRHbPZ+yvPgRH/wfBBKJgJ4WWY70kDoig7/tZpFTEwWfK0TCJSqhiApKPERUdUBhRX1ItARtuFXlS+tlmq8dsrlWo3IkJdYdXVEKMMU3LAWFlN6qLtNL0dTNKfUwGsmHYNIpWmRbMN34fIAGa9rVThUyaqsO6OW0BgeLZM3wdUNqjbIosczM7BwFjnbSxGksclfNSbQdEV9zbLOeEuEbOFNGj4OQ182BjgHoWj8FX0nrjYI3LnqZHvmUySx1t2M/UDnyH6CRHQpoReMILtZCCV/wSttztf8uBfuU=
